import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-air-freight-invoice-audit-recovery",
  "engine": "recovery",
  "title": "Air Freight Invoice Audit & Recovery",
  "shortTitle": "Air Freight Invoice Audit and Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through air freight invoice audit & recovery",
  "industry": "Air Cargo Spend Recovery",
  "uiPort": 4605,
  "apiPort": 5605,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "Air Freight Invoice Audit & Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect airline and forwarder contracts, air waybills, actual and dimensional weight, chargeable weight, rates, surcharges, routing, invoices, disputes, and credits in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "billedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Billed Air Freight",
    "expectedLabel": "Contract-Supported Freight",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Air Freight Invoice Audit & Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("airline-forwarder-contract-library","AFI01","Airline forwarder contract library","Execute airline forwarder contract library using airline and forwarder contracts, air waybills, actual and dimensional weight, chargeable weight, rates, surcharges, routing, invoices, disputes, and credits.","Produce a governed airline forwarder contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Air Waybill","text","Carrier / Air Waybill · Standard Case"],["caseReference","Airline forwarder contract library Reference","text","AFI01-2026-001"],["billedAmount","Billed Air Freight","currency",679000],["supportedAmount","Contract-Supported Freight","currency",583940],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Airline forwarder contract library case","Air waybill ingestion case","Actual weight validation case","Dimensional weight calculation case","Chargeable weight calculation case"]}),
feature("air-waybill-ingestion","AFI02","Air waybill ingestion","Execute air waybill ingestion using airline and forwarder contracts, air waybills, actual and dimensional weight, chargeable weight, rates, surcharges, routing, invoices, disputes, and credits.","Produce a governed air waybill ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Air Waybill","text","Carrier / Air Waybill · Standard Case"],["caseReference","Air waybill ingestion Reference","text","AFI02-2026-001"],["billedAmount","Billed Air Freight","currency",679000],["supportedAmount","Contract-Supported Freight","currency",583940],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Airline forwarder contract library case","Air waybill ingestion case","Actual weight validation case","Dimensional weight calculation case","Chargeable weight calculation case"]}),
feature("actual-weight-validation","AFI03","Actual weight validation","Execute actual weight validation using airline and forwarder contracts, air waybills, actual and dimensional weight, chargeable weight, rates, surcharges, routing, invoices, disputes, and credits.","Produce a governed actual weight validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Air Waybill","text","Carrier / Air Waybill · Standard Case"],["caseReference","Actual weight validation Reference","text","AFI03-2026-001"],["billedAmount","Billed Air Freight","currency",679000],["supportedAmount","Contract-Supported Freight","currency",583940],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Airline forwarder contract library case","Air waybill ingestion case","Actual weight validation case","Dimensional weight calculation case","Chargeable weight calculation case"]}),
feature("dimensional-weight-calculation","AFI04","Dimensional weight calculation","Execute dimensional weight calculation using airline and forwarder contracts, air waybills, actual and dimensional weight, chargeable weight, rates, surcharges, routing, invoices, disputes, and credits.","Produce a governed dimensional weight calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Air Waybill","text","Carrier / Air Waybill · Standard Case"],["caseReference","Dimensional weight calculation Reference","text","AFI04-2026-001"],["billedAmount","Billed Air Freight","currency",679000],["supportedAmount","Contract-Supported Freight","currency",583940],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Airline forwarder contract library case","Air waybill ingestion case","Actual weight validation case","Dimensional weight calculation case","Chargeable weight calculation case"]}),
feature("chargeable-weight-calculation","AFI05","Chargeable weight calculation","Execute chargeable weight calculation using airline and forwarder contracts, air waybills, actual and dimensional weight, chargeable weight, rates, surcharges, routing, invoices, disputes, and credits.","Produce a governed chargeable weight calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Air Waybill","text","Carrier / Air Waybill · Standard Case"],["caseReference","Chargeable weight calculation Reference","text","AFI05-2026-001"],["billedAmount","Billed Air Freight","currency",679000],["supportedAmount","Contract-Supported Freight","currency",583940],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Airline forwarder contract library case","Air waybill ingestion case","Actual weight validation case","Dimensional weight calculation case","Chargeable weight calculation case"]}),
feature("base-rate-reconstruction","AFI06","Base rate reconstruction","Execute base rate reconstruction using airline and forwarder contracts, air waybills, actual and dimensional weight, chargeable weight, rates, surcharges, routing, invoices, disputes, and credits.","Produce a governed base rate reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Air Waybill","text","Carrier / Air Waybill · Standard Case"],["caseReference","Base rate reconstruction Reference","text","AFI06-2026-001"],["billedAmount","Billed Air Freight","currency",679000],["supportedAmount","Contract-Supported Freight","currency",583940],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Airline forwarder contract library case","Air waybill ingestion case","Actual weight validation case","Dimensional weight calculation case","Chargeable weight calculation case"]}),
feature("security-surcharge-audit","AFI07","Security surcharge audit","Execute security surcharge audit using airline and forwarder contracts, air waybills, actual and dimensional weight, chargeable weight, rates, surcharges, routing, invoices, disputes, and credits.","Produce a governed security surcharge audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Air Waybill","text","Carrier / Air Waybill · Standard Case"],["caseReference","Security surcharge audit Reference","text","AFI07-2026-001"],["billedAmount","Billed Air Freight","currency",679000],["supportedAmount","Contract-Supported Freight","currency",583940],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Airline forwarder contract library case","Air waybill ingestion case","Actual weight validation case","Dimensional weight calculation case","Chargeable weight calculation case"]}),
feature("fuel-surcharge-validation","AFI08","Fuel surcharge validation","Execute fuel surcharge validation using airline and forwarder contracts, air waybills, actual and dimensional weight, chargeable weight, rates, surcharges, routing, invoices, disputes, and credits.","Produce a governed fuel surcharge validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Air Waybill","text","Carrier / Air Waybill · Standard Case"],["caseReference","Fuel surcharge validation Reference","text","AFI08-2026-001"],["billedAmount","Billed Air Freight","currency",679000],["supportedAmount","Contract-Supported Freight","currency",583940],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Airline forwarder contract library case","Air waybill ingestion case","Actual weight validation case","Dimensional weight calculation case","Chargeable weight calculation case"]}),
feature("screening-fee-audit","AFI09","Screening fee audit","Execute screening fee audit using airline and forwarder contracts, air waybills, actual and dimensional weight, chargeable weight, rates, surcharges, routing, invoices, disputes, and credits.","Produce a governed screening fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Air Waybill","text","Carrier / Air Waybill · Standard Case"],["caseReference","Screening fee audit Reference","text","AFI09-2026-001"],["billedAmount","Billed Air Freight","currency",679000],["supportedAmount","Contract-Supported Freight","currency",583940],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Airline forwarder contract library case","Air waybill ingestion case","Actual weight validation case","Dimensional weight calculation case","Chargeable weight calculation case"]}),
feature("handling-fee-audit","AFI10","Handling fee audit","Execute handling fee audit using airline and forwarder contracts, air waybills, actual and dimensional weight, chargeable weight, rates, surcharges, routing, invoices, disputes, and credits.","Produce a governed handling fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Air Waybill","text","Carrier / Air Waybill · Standard Case"],["caseReference","Handling fee audit Reference","text","AFI10-2026-001"],["billedAmount","Billed Air Freight","currency",679000],["supportedAmount","Contract-Supported Freight","currency",583940],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Airline forwarder contract library case","Air waybill ingestion case","Actual weight validation case","Dimensional weight calculation case","Chargeable weight calculation case"]}),
feature("minimum-charge-calculation","AFI11","Minimum charge calculation","Execute minimum charge calculation using airline and forwarder contracts, air waybills, actual and dimensional weight, chargeable weight, rates, surcharges, routing, invoices, disputes, and credits.","Produce a governed minimum charge calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Air Waybill","text","Carrier / Air Waybill · Standard Case"],["caseReference","Minimum charge calculation Reference","text","AFI11-2026-001"],["billedAmount","Billed Air Freight","currency",679000],["supportedAmount","Contract-Supported Freight","currency",583940],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Airline forwarder contract library case","Air waybill ingestion case","Actual weight validation case","Dimensional weight calculation case","Chargeable weight calculation case"]}),
feature("routing-service-validation","AFI12","Routing service validation","Execute routing service validation using airline and forwarder contracts, air waybills, actual and dimensional weight, chargeable weight, rates, surcharges, routing, invoices, disputes, and credits.","Produce a governed routing service validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Air Waybill","text","Carrier / Air Waybill · Standard Case"],["caseReference","Routing service validation Reference","text","AFI12-2026-001"],["billedAmount","Billed Air Freight","currency",679000],["supportedAmount","Contract-Supported Freight","currency",583940],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Airline forwarder contract library case","Air waybill ingestion case","Actual weight validation case","Dimensional weight calculation case","Chargeable weight calculation case"]}),
feature("invoice-matching","AFI13","Invoice matching","Execute invoice matching using airline and forwarder contracts, air waybills, actual and dimensional weight, chargeable weight, rates, surcharges, routing, invoices, disputes, and credits.","Produce a governed invoice matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Air Waybill","text","Carrier / Air Waybill · Standard Case"],["caseReference","Invoice matching Reference","text","AFI13-2026-001"],["billedAmount","Billed Air Freight","currency",679000],["supportedAmount","Contract-Supported Freight","currency",583940],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Airline forwarder contract library case","Air waybill ingestion case","Actual weight validation case","Dimensional weight calculation case","Chargeable weight calculation case"]}),
feature("dispute-package","AFI14","Dispute package","Execute dispute package using airline and forwarder contracts, air waybills, actual and dimensional weight, chargeable weight, rates, surcharges, routing, invoices, disputes, and credits.","Produce a governed dispute package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Air Waybill","text","Carrier / Air Waybill · Standard Case"],["caseReference","Dispute package Reference","text","AFI14-2026-001"],["billedAmount","Billed Air Freight","currency",679000],["supportedAmount","Contract-Supported Freight","currency",583940],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Airline forwarder contract library case","Air waybill ingestion case","Actual weight validation case","Dimensional weight calculation case","Chargeable weight calculation case"]}),
feature("carrier-lane-analytics","AFI15","Carrier lane analytics","Execute carrier lane analytics using airline and forwarder contracts, air waybills, actual and dimensional weight, chargeable weight, rates, surcharges, routing, invoices, disputes, and credits.","Produce a governed carrier lane analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Carrier / Air Waybill","text","Carrier / Air Waybill · Standard Case"],["caseReference","Carrier lane analytics Reference","text","AFI15-2026-001"],["billedAmount","Billed Air Freight","currency",679000],["supportedAmount","Contract-Supported Freight","currency",583940],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"billedAmount",subjects:["Airline forwarder contract library case","Air waybill ingestion case","Actual weight validation case","Dimensional weight calculation case","Chargeable weight calculation case"]})
]);
